# Generated by Django 4.2.2 on 2023-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=500)),
                ('comapny', models.CharField(max_length=256)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
